#include "circular_queue_primitive.h"

IMPLEMENT_CIRCULAR_QUEUE_TYPE(int, Int)
IMPLEMENT_CIRCULAR_QUEUE_TYPE(float, Float)
IMPLEMENT_CIRCULAR_QUEUE_TYPE(double, Double)
IMPLEMENT_CIRCULAR_QUEUE_TYPE(long long, LongLong)
IMPLEMENT_CIRCULAR_QUEUE_TYPE(char, Char)
IMPLEMENT_CIRCULAR_QUEUE_TYPE(short, Short)
